create table users(id int(13), username varchar(40), password varchar(60), salt varchar(60));


CREATE TABLE RBAC_SERVICE (
	SERVICE_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	SERVICE_NAME VARCHAR(40),
	SERVICE_TYPE VARCHAR(30),
	PRIMARY KEY (SERVICE_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1001 DEFAULT CHARSET=latin1;

CREATE TABLE RBAC_PERMISSION (
	PERMISSION_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	SERVICE_ID INTEGER,
	PERMISSION_NAME VARCHAR(60),
	PRIMARY KEY (PERMISSION_ID)
) ENGINE=InnoDB AUTO_INCREMENT=11001 DEFAULT CHARSET=latin1;


INSERT INTO `rbac_service` (`SERVICE_ID`,`SERVICE_NAME`,`SERVICE_TYPE`) VALUES
 (1001,'CAT_BREED','VIEW'),
 (1002,'DOG_BREED','VIEW');
 
INSERT INTO `RBAC_PERMISSION` (`PERMISSION_ID`,`SERVICE_ID`,`PERMISSION_NAME`) VALUES
 (11001,1001,'ROLE_CAT_VIEW'),
 (11002,1002,'ROLE_DOG_VIEW');

 
 
CREATE TABLE RBAC_ROLE (
	ROLE_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	ROLE_NAME VARCHAR(60),
	PRIMARY KEY (ROLE_ID)
) ENGINE=InnoDB AUTO_INCREMENT=22001 DEFAULT CHARSET=latin1;

INSERT INTO `RBAC_ROLE` (`ROLE_ID`,`ROLE_NAME`) VALUES
 (22001,'VIEW_ALL_PET');


CREATE TABLE ROLE_PERMISSION (
	SR_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	ROLE_ID INTEGER,
	PERMISSION_ID INTEGER,
	PRIMARY KEY (SR_ID)
) ENGINE=InnoDB AUTO_INCREMENT=30001 DEFAULT CHARSET=latin1;

INSERT INTO `ROLE_PERMISSION` (`SR_ID`, `ROLE_ID`,`PERMISSION_ID`) VALUES
 (30001, 22001, 11001),
 (30002, 22001, 11002);

CREATE TABLE USER_ROLE(
	SR_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	USER_ID VARCHAR(20),
	ROLE_ID INTEGER,
	PRIMARY KEY (SR_ID)
) 

INSERT INTO `USER_ROLE` (`SR_ID`, `USER_ID`,`ROLE_ID`) VALUES
(70001, 1, 22001);

